use_frameworks!

target 'ChurchillQuotes_Example' do
  pod 'ChurchillQuotes', :path => '../'

  target 'ChurchillQuotes_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
